name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{c,h} | xargs clang-format -i --style=file --verbose && git diff --exit-code

      - name: Build application
        run: make && make test
        
      - name: ctest
        run: bin/mygeomprogram-test 
